# Generated by Django 6.0.4 on 2026-04-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.AddField(
            model_name="user",
            name="last_active",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Последняя активность"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_notification_sent",
            field=models.DateTimeField(
                blank=True,
                help_text="Время последнего отправленного уведомления",
                null=True,
                verbose_name="Последнее уведомление",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_habits_created",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Всего привычек создано"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="ID чата пользователя в Telegram для отправки уведомлений",
                max_length=100,
                null=True,
                verbose_name="Telegram Chat ID",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["telegram_chat_id"], name="users_user_telegra_1e47e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username"], name="users_user_usernam_65d164_idx"
            ),
        ),
    ]
