# Generated by Django 6.0.4 on 2026-04-19 16:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ["time", "place"],
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
        migrations.AddField(
            model_name="habit",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="habit",
            name="execution_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Общее количество выполнений привычки",
                verbose_name="Количество выполнений",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Активна ли привычка в данный момент",
                verbose_name="Активна",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="last_executed",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата и время последнего выполнения привычки",
                null=True,
                verbose_name="Последнее выполнение",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="streak_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Количество дней подряд выполнения привычки",
                verbose_name="Серия (дни)",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(
                help_text="Действие, которое представляет собой привычка",
                max_length=255,
                verbose_name="Действие",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="duration_seconds",
            field=models.PositiveSmallIntegerField(
                default=120,
                help_text="Время, которое пользователь потратит на выполнение (не более 120 секунд)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(120),
                ],
                verbose_name="Время на выполнение (секунды)",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                default=False,
                help_text="Отмечает, является ли привычка приятной (вознаграждением)",
                verbose_name="Приятная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Можно публиковать в общий доступ для других пользователей",
                verbose_name="Публичная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Периодичность выполнения привычки (от 1 до 7 дней)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ],
                verbose_name="Периодичность (дни)",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                db_index=True,
                help_text="Место, в котором необходимо выполнять привычку",
                max_length=255,
                verbose_name="Место",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Привычка, которая связана с другой привычкой (для полезных привычек)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_to",
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Чем пользователь должен себя вознаградить после выполнения",
                max_length=255,
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                db_index=True,
                help_text="Время, когда необходимо выполнять привычку",
                verbose_name="Время",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                help_text="Владелец привычки",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["user", "is_active"], name="habits_habi_user_id_f5e729_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["user", "is_public"], name="habits_habi_user_id_175c9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["time", "periodicity"], name="habits_habi_time_5cc0d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["user", "last_executed"], name="habits_habi_user_id_9b760b_idx"
            ),
        ),
    ]
