# Generated by Django 6.0.4 on 2026-04-19 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_options_habit_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время выполнения"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Заметки"),
                ),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="habits.habit",
                        verbose_name="Привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выполнение привычки",
                "verbose_name_plural": "Выполнения привычек",
                "ordering": ["-executed_at"],
            },
        ),
    ]
